databases:
- cluster_name: wallfair
  engine: MONGODB
  name: wallfair
  production: true
  version: "4"
- cluster_name: redis
  engine: REDIS
  name: redis
  production: true
  version: "6"
- cluster_name: prod-db
  db_name: testdb
  db_user: doadmin
  engine: PG
  name: prod-db
  production: true
  version: "13"
envs:
- key: REDIS_CONNECTION
  scope: RUN_AND_BUILD_TIME
  value: ${redis.DATABASE_URL}
name: staging-backend
region: fra
services:
- envs:
  - key: JWT_KEY
    scope: RUN_AND_BUILD_TIME
    value: $JWT_KEY
  - key: TWILIO_ACC_SID
    scope: RUN_AND_BUILD_TIME
    value: $TWILIO_ACC_SID
  - key: TWILIO_AUTH_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: $TWILIO_AUTH_TOKEN
  - key: TWILIO_SID
    scope: RUN_AND_BUILD_TIME
    value: $TWILIO_SID
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: STAGING
  - key: VERIFY_URL
    scope: RUN_AND_BUILD_TIME
    value: https://staging.wallfair.io/
  - key: GMAIL_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: noreply@wallfair.io
  - key: GMAIL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: $GMAIL_PASSWORD
  - key: POSTGRES_CA
    scope: RUN_AND_BUILD_TIME
    value: /usr/src/app/ssl/postgres-prod.crt
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: doadmin
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: prod-db-do-user-9290946-0.b.db.ondigitalocean.com
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: $STAGING_POSTGRES_DB
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: $POSTGRES_PASSWORD
  - key: POSTGRES_SSL
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: "25060"
  - key: BACKEND_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://staging-zeaec.ondigitalocean.app"
  - key: TWITCH_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: $TWITCH_CLIENT_ID
  - key: TWITCH_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: $TWITCH_CLIENT_SECRET
  - key: TWITCH_CALLBACK_SECRET
    scope: RUN_AND_BUILD_TIME
    value: $TWITCH_CALLBACK_SECRET
  - key: ADMIN_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: $ADMIN_USERNAME
  - key: ADMIN_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: $ADMIN_PASSWORD
  - key: GOOGLE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: $GOOGLE_API_KEY
  - key: DB_CONNECTION
    scope: RUN_AND_BUILD_TIME
    value: $STAGING_MONGO_DB_URL
  - key: AUTH0_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: $AUTH0_DOMAIN
  - key: AUTH0_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: $AUTH0_CLIENT_ID
  - key: AUTH0_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: $AUTH0_CLIENT_SECRET
  - key: AUTH0_AUDIENCE
    scope: RUN_AND_BUILD_TIME
    value: $AUTH0_AUDIENCE
  - key: AUTH0_CONNECTION_ID
    scope: RUN_AND_BUILD_TIME
    value: $AUTH0_CONNECTION_ID
  - key: AWS_S3_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: $AWS_S3_CLIENT_ID
  - key: AWS_S3_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: $AWS_S3_CLIENT_SECRET
  - key: AWS_S3_CLIENT_BUCKET
    scope: RUN_AND_BUILD_TIME
    value: $AWS_S3_CLIENT_BUCKET
  - key: AWS_S3_CLIENT_REGION
    scope: RUN_AND_BUILD_TIME
    value: $AWS_S3_CLIENT_REGION
  http_port: 80
  image:
    registry_type: DOCR
    repository: backend
    tag: $VERSION
  instance_count: 2
  instance_size_slug: professional-xs
  name: staging
  routes:
  - path: /
  source_dir: /