apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: playmoney
commonLabels:
  environment: playmoney

configMapGenerator:
  - name: backend-config
    behavior: merge
    envs:
      - environment