BEGIN;
CREATE TABLE IF NOT EXISTS user_cashbacks (ID SERIAL PRIMARY KEY, userId varchar(255) NOT NULL, type varchar(255), amount NUMERIC, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, UNIQUE(userId, type));
COMMIT;
