apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
        - image: registry.digitalocean.com/wallfair/backend_k8s
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1300m
            requests:
              cpu: 1000m
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 3
          name: backend
          envFrom:
          - configMapRef:
              name: backend-config
          - configMapRef:
              name: app-secrets
          ports:
            - containerPort: 8000

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage: 50

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: staging
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
